export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window',
    'a fortune-telling shiba inu reading your fate in a giant hamburger',
    'a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea',
    'Two futuristic towers with a skybridge covered in lush foliage',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubiks cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
  ];

  export const surpriseVideoPrompts = [
    "A day in my life: from sunrise to sunset.",
"My top 5 favorite books and why I recommend them.",
"Exploring a hidden gem in my city: a local hotspot.",
"Cooking challenge: trying a new recipe for the first time.",
"Q&A session: answering your burning questions about me.",
"DIY project: transforming something old into something new.",
"Behind the scenes of a typical day in my creative process.",
"Reviewing the latest tech gadgets or apps.",
"A travel vlog: my favorite memories from a recent trip.",
"Discussing my personal fitness journey and favorite workouts.",
"Reacting to funny or heartwarming viral videos.",
"My top 10 favorite movies of all time.",
"A tour of my workspace or creative setup.",
"Attempting a 30-day challenge and documenting the progress.",
"Interviewing a friend or family member about their passions.",
"Sharing my favorite productivity tips and hacks.",
"Exploring a nearby nature spot: hiking or nature walk adventure.",
"Discussing current events or hot topics with a personal perspective.",
"A tutorial: teaching a skill or craft I'm passionate about.",
"My morning routine: tips for a productive start to the day.",
"Creating and sharing a playlist of my favorite music.",
"Reviewing and testing out budget-friendly products.",
"A day of self-care: pampering and relaxation routine.",
"Exploring a new hobby or interest for the first time.",
"Reacting to old photos or videos from my past.",
"Discussing my favorite quotes and the inspiration behind them.",
"Sharing my go-to healthy recipes for busy days.",
"A challenge: trying to live without a specific technology for a day.",
"A look back at my achievements and goals for the future.",
"Creating a time-lapse of a creative project from start to finish."
  ];

  export const surpriseAudioPrompt = [
    "Compose a relaxing ambient track for meditation.",
"Generate a futuristic soundtrack for a sci-fi scene.",
"Create a jazzy and upbeat background music for a vlog.",
"Generate an electronic dance music (EDM) track with a catchy melody.",
"Produce a calming nature-inspired soundscape.",
"Generate a suspenseful and mysterious audio snippet for storytelling.",
"Compose a nostalgic and emotional piano piece.",
"Create an energetic and motivational track for workout videos.",
"Generate a whimsical and playful tune suitable for animation.",
"Produce a space-themed ambient track for relaxation.",
"Compose a lo-fi hip-hop beat for studying or relaxing.",
"Generate a tropical and upbeat summer vibe track.",
"Create a dynamic and adventurous orchestral piece.",
"Produce a retro-inspired synthwave track.",
"Generate an audio backdrop for a tech-related video or podcast.",
"Compose a dreamy and ethereal instrumental piece.",
"Create a custom ringtone or notification sound.",
"Generate a calming rainforest soundscape with subtle animal noises.",
"Produce an uplifting and positive acoustic guitar composition.",
"Compose a Halloween-themed spooky soundtrack.",
"Generate a rhythmic and pulsating electronic beat for gaming content.",
"Create an audio background for a time-lapse or fast-forward video.",
"Produce a mellow and introspective soundtrack for reflective content.",
"Generate a cheerful and upbeat track suitable for a travel montage.",
"Compose a dynamic and epic battle music for gaming or action scenes.",
"Create an audio logo or intro jingle for your brand.",
"Generate a serene and contemplative audio piece for mindfulness.",
"Produce a holiday-themed festive jingle.",
"Compose a cinematic score for a short film or animation.",
"Generate a glitchy and experimental audio track for avant-garde content."
  ]

export const faqArray = [
  {
    question:"What is the minimum subscription plan for PRO membership?",
    answer: "You have to visit our planes, there is deferent type of plans, minmum plan starting from 20$ per month",
    active: 1
  },
  {
    question: "Can I cancel my subscription plan? is it manageble?",
    answer: "Yes user can perchase a plane by his convinience, and after that, he/she could manage there plan also",
    active: 2
  },
  {
    question: "Is there any free generation limit, or Can I generate freely?",
    answer: "There is free generation,per user can generate upto 5 free credit, after free credits, are end you have to move for PRO",
    active: 3,
  },
  {
    question: "Can we generate Ai Images?",
    answer: "Yes of course, you can, you can generate , music, video, Image, text, code what your imagenation is",
    active: 4,
  },
  {
    question: "How do I sign up for AI Studio?",
    answer: "To create an account, click on the SignUp button on the homepage. Fill in the required information",
    active: 5,
  }
]

export const maxCreditCount = 5;